### ISSUE TITLE
Assignment 2: Text size

### ISSUE THREAD

**Issue by pdirmeyer** [desmond-gray/Assignment_2#3]
Some of the text is quite small, especially the titles for your panels.  You can control the size of text, and many other text properties, easily. See https://matplotlib.org/stable/tutorials/text/text_intro.html for a general discussion of text in `matplotlib` plots, and https://matplotlib.org/stable/api/text_api.html#matplotlib.text.Text for options to control font size, style, weight, etc.

**Comment by desmond-gray** [comment]
I've increased the font size of each plot title to 20
